//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace textsl.Actions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class slStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal slStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("textsl.Actions.slStrings", typeof(slStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enters into chat mode. In chat mode all you type is understood to be your chat message..
        /// </summary>
        internal static string schat {
            get {
                return ResourceManager.GetString("schat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crouch..
        /// </summary>
        internal static string scrouch {
            get {
                return ResourceManager.GetString("scrouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exits from the current mode to default mode.If running in default mode, logs out..
        /// </summary>
        internal static string sexit {
            get {
                return ResourceManager.GetString("sexit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You start flying..
        /// </summary>
        internal static string sfly {
            get {
                return ResourceManager.GetString("sfly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start or stop following a user..
        /// </summary>
        internal static string sfollow {
            get {
                return ResourceManager.GetString("sfollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print help message for commands and modes..
        /// </summary>
        internal static string shelp {
            get {
                return ResourceManager.GetString("shelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump..
        /// </summary>
        internal static string sjump {
            get {
                return ResourceManager.GetString("sjump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gives the coordinates of where you are..
        /// </summary>
        internal static string slocate {
            get {
                return ResourceManager.GetString("slocate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to Secondlife..
        /// </summary>
        internal static string slogin {
            get {
                return ResourceManager.GetString("slogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logsout and quits from Secondlife..
        /// </summary>
        internal static string slogout {
            get {
                return ResourceManager.GetString("slogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to a person or object, or in a direction: west, east, north or south..
        /// </summary>
        internal static string smove {
            get {
                return ResourceManager.GetString("smove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Mute or unmute a user..
        /// </summary>
        internal static string smute {
            get {
                return ResourceManager.GetString("smute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the Range of how far you want to see, how many objects and people you want to see..
        /// </summary>
        internal static string srange {
            get {
                return ResourceManager.GetString("srange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resets current user login information. Use this when you want to re-login as a different user..
        /// </summary>
        internal static string sreset {
            get {
                return ResourceManager.GetString("sreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say a message for everyone in the neighborhood to hear..
        /// </summary>
        internal static string ssay {
            get {
                return ResourceManager.GetString("ssay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sit on the ground or on an object..
        /// </summary>
        internal static string ssit {
            get {
                return ResourceManager.GetString("ssit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stand up..
        /// </summary>
        internal static string sstand {
            get {
                return ResourceManager.GetString("sstand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancels a particular action..
        /// </summary>
        internal static string sstop {
            get {
                return ResourceManager.GetString("sstop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You stop flying..
        /// </summary>
        internal static string sstopflying {
            get {
                return ResourceManager.GetString("sstopflying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleport to a location..
        /// </summary>
        internal static string steleport {
            get {
                return ResourceManager.GetString("steleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests your basic command knowledge of navigation and talking..
        /// </summary>
        internal static string stest1 {
            get {
                return ResourceManager.GetString("stest1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teaches you how to navigate using basic commands move, sit, stand..
        /// </summary>
        internal static string stutorial1 {
            get {
                return ResourceManager.GetString("stutorial1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finds out in which direction an object or a building or a person is..
        /// </summary>
        internal static string swhere {
            get {
                return ResourceManager.GetString("swhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whisper a message to an avatar..
        /// </summary>
        internal static string swhisper {
            get {
                return ResourceManager.GetString("swhisper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To enter chat mode, type &quot;chat&quot;. To exit type &quot;exit&quot;..
        /// </summary>
        internal static string uchat {
            get {
                return ResourceManager.GetString("uchat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Crouch type &quot;crouch&quot;.
        /// </summary>
        internal static string ucrouch {
            get {
                return ResourceManager.GetString("ucrouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exits from the tutorial mode to default mode.If running in default mode, logs out and quits.
        ///To exit type in &quot;exit&quot;.
        /// </summary>
        internal static string uexit {
            get {
                return ResourceManager.GetString("uexit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To start flying type: &quot;fly&quot;.
        /// </summary>
        internal static string ufly {
            get {
                return ResourceManager.GetString("ufly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To start following an avatar, type &quot;follow avatar name&quot;.
        /// </summary>
        internal static string ufollow {
            get {
                return ResourceManager.GetString("ufollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &quot;help&quot; to get a list of available all commands and modes or type &quot;help command name&quot; to get detailed help of a specific command or mode.
        /// </summary>
        internal static string uhelp {
            get {
                return ResourceManager.GetString("uhelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Jump type &quot;jump&quot;.
        /// </summary>
        internal static string ujump {
            get {
                return ResourceManager.GetString("ujump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To locate the coordinates of yourself, type in &quot;locate&quot;.
        /// </summary>
        internal static string ulocate {
            get {
                return ResourceManager.GetString("ulocate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To login to Second Life, type &quot;login first name last name password&quot;
        ///You can just type &quot;login&quot; to login as the avatar you previously logged in..
        /// </summary>
        internal static string ulogin {
            get {
                return ResourceManager.GetString("ulogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To logout and quit Second Life, type &quot;quit&quot;.
        /// </summary>
        internal static string ulogout {
            get {
                return ResourceManager.GetString("ulogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &quot;west/east/north/south&quot; to move 5 meters in a direction. Or Type &quot;west distance/east distance/north distance/south distance&quot; to move a specific distance in that direction.
        ///To move to an avatar type &quot;move to avatar name&quot;.
        ///To move to an object type &quot;move to object name&quot;..
        /// </summary>
        internal static string umove {
            get {
                return ResourceManager.GetString("umove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Mute an avatar, type &quot;Mute avatar name&quot;; to Mute all, type &quot;mute all&quot;.
        /// </summary>
        internal static string umute {
            get {
                return ResourceManager.GetString("umute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the Range of how far you want to see, how many objects and people you want to see at a time.
        ///You can type &quot;range &apos;distance&apos; &apos;number of objects&apos; &apos;number of people&apos;.
        /// </summary>
        internal static string urange {
            get {
                return ResourceManager.GetString("urange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset when you want to re-login as a different user.
        ///To reset current login information type &quot;reset&quot;.
        /// </summary>
        internal static string ureset {
            get {
                return ResourceManager.GetString("ureset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To communicate to everyone near you, type &quot;say message&quot;.
        ///Or simply begin your sentence with a double quote..
        /// </summary>
        internal static string usay {
            get {
                return ResourceManager.GetString("usay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To sit on ground, type &quot;sit&quot;
        ///To sit on an object, type &quot;sit on object name&quot;.
        /// </summary>
        internal static string usit {
            get {
                return ResourceManager.GetString("usit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Stand up, type &quot;stand&quot;.
        /// </summary>
        internal static string ustand {
            get {
                return ResourceManager.GetString("ustand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop works with following arguments: 
        ///Type &quot;stop following&quot; to stop following an avatar you were following.
        ///Type &quot;stop flying&quot; to stop flying.
        ///Type &quot;stop mute avatar name&quot; or &quot;stop mute all&quot; to unmute..
        /// </summary>
        internal static string ustop {
            get {
                return ResourceManager.GetString("ustop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To stop flying type: &quot;stop-flying&quot;.
        /// </summary>
        internal static string ustopflying {
            get {
                return ResourceManager.GetString("ustopflying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To teleport to a location, type &quot;teleport to location name&quot;. Some location names of your interest can be: Help Island Public, Fishermans Cove, Virtual Ability.
        /// </summary>
        internal static string uteleport {
            get {
                return ResourceManager.GetString("uteleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests your basic command knowledge of navigation and talking..
        /// </summary>
        internal static string utest1 {
            get {
                return ResourceManager.GetString("utest1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teaches you the basic commands of navigation and communication in Second Life..
        /// </summary>
        internal static string ututorial1 {
            get {
                return ResourceManager.GetString("ututorial1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To find out where an object, building or a person is, type &quot;where is object/person name&quot;.
        /// </summary>
        internal static string uwhere {
            get {
                return ResourceManager.GetString("uwhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To whisper a message only to a specific avatar, type &quot;whisper to &apos;avatar name&apos; &apos;message&apos; &quot;
        ///This starts your session with the avatar and then you can just type &quot;whisper message&quot; to whisper to that avatar..
        /// </summary>
        internal static string uwhisper {
            get {
                return ResourceManager.GetString("uwhisper", resourceCulture);
            }
        }
    }
}
